"""make topic nullable

Revision ID: c851a4c8ffc1
Revises: 813581af98ec
Create Date: 2023-07-09 15:18:23.108518

"""
import sqlalchemy as sa
from alembic import op

revision = 'c851a4c8ffc1'
down_revision = '813581af98ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
