"""update

Revision ID: eaa1c071a28a
Revises: d87be15f5f3a
Create Date: 2023-07-09 13:05:05.395221

"""
import sqlalchemy as sa
from alembic import op

revision = 'eaa1c071a28a'
down_revision = 'd87be15f5f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('topic', sa.Enum('ORGANIZATION', 'COMMUNICATION', 'LEADERSHIP', 'CULTURE_AND_VALUES', 'WELLBEING', name='interviewtopic'), nullable=False))
    op.add_column('answer', sa.Column('score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'score')
    op.drop_column('answer', 'topic')
    # ### end Alembic commands ###
