apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
        - name: api
          image: gcr.io/remote-how-ai/github.com/ai-ai-boyzz/medrzec-ai
          env:
            - name: DATABASE_PATH
              value: "sqlite:////data/db.sqlite"
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: api
                  key: SERVICE_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api
                  key: OPENAI_API_KEY
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api
                  key: PINECONE_API_KEY
            - name: PINECONE_ENV
              valueFrom:
                secretKeyRef:
                  name: api
                  key: PINECONE_ENV
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api
                  key: GOOGLE_CLIENT_ID
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api
                  key: SLACK_CLIENT_ID
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api
                  key: SLACK_CLIENT_SECRET
            - name: SLACK_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: api
                  key: SLACK_REDIRECT_URI
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: data
