from langchain.memory import ConversationBufferMemory


class CleanConversationMemory(ConversationBufferMemory):
    """
    This custom conversation memory implementation aims to remove fake user replies
    generated by the AI
    """

    def save_context(self, inputs: dict[str, str], outputs: dict[str, str]) -> None:
        outputs = {key: clean_message(value) for key, value in outputs.items()}
        super().save_context(inputs, outputs)


def clean_message(text: str) -> str:
    lines = []

    for line in text.splitlines():
        if line.startswith("Human:"):
            print("Fixed AI reply (included a human response)")
            break

        lines.append(line)

    return "\n".join(lines)
